// Generated by CoffeeScript 1.6.3
var spawn;

spawn = require('child_process').spawn;

module.exports = function(args) {
  var child, cmd, message, title;
  if (args == null) {
    args = {};
  }
  cmd = 'terminal-notifier.app/Contents/MacOS/terminal-notifier';
  title = args.title, message = args.message;
  return child = spawn(cmd, ['-title', title, '-message', message]);
};
